[Settings]
ID = "Staging-I"
[build]
  # This will be your default build command
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true
  
[build.environment]
  domainkey = "flowzdigital.com"  
